### ISSUE TITLE
Avoid running `terraform workspace select [env]` during `terrahub run` if already selected

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#295]
## Describe the Feature

Avoid running `terraform workspace select [env]` during `terrahub run` if already selected

## Expected Behavior

As part of optimization and speed up effort, please update `terrahub run` to avoid running `terraform workspace select [env]` if terraform workspace `[env]` is already selected

**Comment by KanoniPan** [comment]
Test Passed:
Next steps were performed:
- `thub run`
<img width="1126" alt="2018-09-14 15 27 30" src="https://user-images.githubusercontent.com/35734669/45550371-509b5480-b833-11e8-8f4d-8c8892e8800a.png">

As you can see on the screenshot `terraform select` action wasn't performed, because `default` workspace was already selected

- `thub workspace -e dev`
- `thub run -e dev`
<img width="1119" alt="2018-09-14 15 28 53" src="https://user-images.githubusercontent.com/35734669/45550266-0ade8c00-b833-11e8-9793-be9f1afccf05.png">

As you can see on the screenshot `terraform select` action wasn't performed, because `dev` workspace was already selected

**Comment by eistrati** [comment]
Checked.
