### ISSUE TITLE
Add command in `terrahub` to manage global config

### ISSUE THREAD

**Issue by Leichtwind** [TerraHubCorp/terrahub#303]
## Describe the Feature

I guess it would be nice if in `terrahub` cli was a command that allows to print to console or to modify the global `terrahub` config. Why?

- This command would make it easier for users to add, change or remove `thub token` and `.terrahub` config format. 
- It would be nice if users didn't have to use 3rd party programs to manage global `terrahub` config.

## Expected Behaviour

1. `terrahub configure hook.apply.after="./script/upload.sh $THUB_BUILD_PATH $THUB_S3_PATH"` ==> will update root / project config with `hook.apply.after` as key and `./script/upload.sh $THUB_BUILD_PATH $THUB_S3_PATH` as value
2. `terrahub configure build.phases.build.commands[]="echo \"BUILD: Running build step\"" build.phases.build.commands[]="./script/compile.sh" --component s3_bucket` ==> will update local / component config with `build.phases.build.commands` as key and `echo "BUILD: Running build step"` and `./script/compile.sh as array values`
3. `terrahub configure token="false" --global` ==> will update global config with `token` as key and `false` as value

**Comment by Leichtwind** [comment]
@eistrati I would like to know what do you think about this idea?

**Comment by eistrati** [comment]
@Leichtwind @ddimitrioglo I believe this is a great idea, but why limit only to `global` config? Let's extend the feature set and functionality to all types of config: `global`, `root` / `project` and `local` / `component` ;) Let's brainstorm it during our next call and come up with **Expected Behavior**

**Comment by eistrati** [comment]
Expected Behavior:
1. `terrahub configure hook.apply.after="./script/upload.sh $THUB_BUILD_PATH $THUB_S3_PATH"` ==> will update root / project config with `hook.apply.after` as key and `./script/upload.sh $THUB_BUILD_PATH $THUB_S3_PATH` as value
2. `terrahub configure build.phases.build.commands[]="echo \"BUILD: Running build step\"" build.phases.build.commands[]="./script/compile.sh" --component s3_bucket` ==> will update local / component config with `build.phases.build.commands` as key and `echo "BUILD: Running build step"` and `./script/compile.sh` as array values
3. `terrahub configure token="false" --global` ==> will update global config with `token` as key and `false` as value

**Comment by eistrati** [comment]
Checked.
