### ISSUE TITLE
Variable precedence / order for configuration values and environment variables

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terrahub#398]
## Describe the Feature

Variable precedence / order for configuration values and environment variables

## Expected Behavior

Variable precedence / order for configuration values and environment variables:
1. global configuration (stored in `~/.terrahub/.terraform.json`)
2. project configuration will overwrite global one (stored in root of the project, `.terrahub.yml` or `.terrahub.json` file)
3. component configuration will overwrite project one (stored in each component, `.terrahub.yml` or `.terrahub.json` file)
4. in all above use cases, if workspace is defined, it will overwrite `default` workspace
5. environment variables defined externally will be overwritten by environment variables defined in global config, further overwritten by ones defined in project config, and further overwritten by ones defined in component config
6. values passed through command line will overwrite any corresponding environment variables or corresponding configuration in config files (see order in steps 1 through 3)

NOTE: This rule is designed to be consistent with terraform's [variable precedence](https://www.terraform.io/docs/configuration/variables.html#variable-precedence)

**Comment by KanoniPan** [comment]
Expected Behavior passed,
project configuration overwrites global one, component configuration overwrites project
if workspace is defined it overwrites `default` one
environment variables defined externally are overwritten by environment variables defined in global config etc.
values passed through command line will overwrite any corresponding environment variables or corresponding configuration in config files
for example`thub plan "region:us-east-2"`

**Comment by ddimitrioglo** [comment]
@KanoniPan Where is the implementation PR?

**Comment by ddimitrioglo** [comment]
@eistrati As @KanoniPan has explained me in private, this task was just to make sure that everything is working as you described. 
Do we moved him to QA? Or there is nothing more important for him?

P.S. My concern here that he wasted his time, @Leichtwind's and mine, in order to validate `Variable precedence` which were discussed at the project beginning and already implemented.

**Comment by eistrati** [comment]
Checked.
