### ISSUE TITLE
Refactor TerraHub CLI code to be directly used in Lambda Deployer

### ISSUE THREAD

**Issue by avozicov** [TerraHubCorp/terrahub#647]

**Comment by Leichtwind** [comment]
Currently code base of TerraHub CLI is just literally copied and adopted to be used in Cloud Deployer.

This approach brings huge inconvenience: code base of Cloud Deployer needs to be permanently updated separately of TerraHub CLI whenever changes happen in TerraHub CLI.

To resolve this issue the following approach should be used:
- TerraHub CLI has abstract modules that are not specified neither for local, neither for cloud or whatever else execution
- These modules are exported in npm terrahub package
- TerraHub CLI implements required modules according to its default approach
- Cloud Deployer as AWS Lambda implements modules according to its specific approach
- Whatever else Cloud or other Deployers (Google Function, Azure etc.) implement modules according to their specific approaches

I recommend to take look on [Bridge design pattern](https://refactoring.guru/design-patterns/bridge). It might be helpful with a very high chance

**Comment by eistrati** [comment]
Based on our recent conversation, we are identifying the following use cases:
1. THUB_TOKEN (or related config value) is missing / empty / invalid
2. ES is turned on/off
- w/out cloud deployer
- w/ cloud deployer
3. `cloudAccount` config is set (or is NOT set) in `.terrahub.yml`

We also discussed that `terrahub run --cloud` might be changed in near future, but as of now it's ok to leave it like this. When this command is executed, the following workflow is expected:
1. Check if `cloudAccount` is missing / empty (if positive, then stop execution with failure message)
2. Check if `cloudAccount` value returned by TerraHub API is empty / invalid (if positive, then stop execution with failure message)
3. Move `start` and `stop` signals for every execution of terrahub component outside of each worker
4. When `--cloud` is enabled, instead of starting worker for terrahub component, start an async lambda function as part of TerraHub API (thub > deploy > aws) with auto retry setting equal to zero
5. When lambda function is started, remove default AWS credentials from inside the lambda environment

Open questions:
1. Let's figure out how `terrahub run --cloud` receives back results from async lambda (in both cases, either if it succeeded or failed)
2. Let's figure out how `terrahub run --cloud` manages use case when lambda fails silently or gets into timeout

**Comment by eistrati** [comment]
Checked.
